name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish NuGet packages (1/2 Pack)
      run: dotnet pack --configuration Release
    - name: Publish NuGet packages (2/2 Publish)
      run: dotnet nuget push "bin/Release/TestNuGetPackage.0.1.0.nupkg" --source "github"
